CREATE TABLE `Airport` (
  `airportId` int(11) NOT NULL AUTO_INCREMENT,
  `waypointId` int(11) DEFAULT NULL,
  `icao` varchar(4) DEFAULT NULL,
  `name` varchar(80) DEFAULT NULL,
  `country` varchar(45) DEFAULT NULL,
  `remarks` mediumtext,
  `freqATIS` int(10) unsigned DEFAULT NULL,
  `freqTower` int(10) unsigned DEFAULT NULL,
  `freqApproach` int(10) unsigned DEFAULT NULL,
  `freqGround` int(10) unsigned DEFAULT NULL,
  `freqClearance` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`airportId`),
  UNIQUE KEY `airportId_UNIQUE` (`airportId`),
  KEY `WaypointFK_idx` (`waypointId`),
  CONSTRAINT `AirportWaypointFK` FOREIGN KEY (`waypointId`) REFERENCES `Waypoint` (`waypointId`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Store airport related data';

CREATE TABLE `Aircraft` (
  `aircraftId` int(11) NOT NULL AUTO_INCREMENT,
  `manufacturer` varchar(45) NOT NULL,
  `model` varchar(45) NOT NULL,
  `variant` varchar(45) NOT NULL,
  `icao` varchar(4) NOT NULL,
  `type` int(11) NOT NULL,
  `vStall` int(10) unsigned DEFAULT NULL,
  `vRotation` int(10) unsigned DEFAULT NULL,
  `vClimb` int(10) unsigned DEFAULT NULL,
  `vFlapsLimit` int(10) unsigned DEFAULT NULL,
  `vLanding` int(10) unsigned DEFAULT NULL,
  `shortestRunwayFt` int(10) unsigned DEFAULT NULL,
  `lbsTakeOffMax` int(10) unsigned DEFAULT NULL,
  `lbsEmpty` int(10) unsigned DEFAULT NULL,
  `lbsFuelMax` int(10) unsigned DEFAULT NULL,
  `paxMax` int(10) unsigned DEFAULT NULL,
  `ceilingFt` int(10) unsigned DEFAULT NULL,
  `rangeNm` int(10) unsigned DEFAULT NULL,
  `enduranceMinutes` int(10) unsigned DEFAULT NULL,
  `engineType` int(11) DEFAULT NULL,
  `engineCount` int(10) unsigned DEFAULT NULL,
  `pphCruise` int(10) unsigned DEFAULT NULL,
  `pphMax` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`aircraftId`),
  UNIQUE KEY `aircraftId_UNIQUE` (`aircraftId`),
  KEY `manufacturer` (`model`,`variant`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stores Aircraft info including performance data which can be used to predict required fuel quantities for a flight.';

CREATE TABLE `Flight` (
  `flightId` int(11) NOT NULL AUTO_INCREMENT,
  `pilotId` int(11) DEFAULT NULL,
  `aircraftId` int(11) DEFAULT NULL,
  `runwayDepId` int(11) DEFAULT NULL,
  `runwayArrId` int(11) DEFAULT NULL,
  `runwayAltId` int(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `flightNotes` mediumtext,
  `wxRating` int(11) DEFAULT NULL,
  `onDateUTC` datetime DEFAULT NULL,
  `offDateUTC` datetime DEFAULT NULL,
  `minutesDay` int(10) unsigned DEFAULT NULL,
  `minutesNight` int(10) unsigned DEFAULT NULL,
  `depCloudCeiling` int(10) unsigned DEFAULT NULL,
  `depVisDistance` int(10) unsigned DEFAULT NULL,
  `depOAT` int(11) DEFAULT NULL,
  `depWindMagBearing` int(10) unsigned DEFAULT NULL,
  `depWindSpeed` int(10) unsigned DEFAULT NULL,
  `depBarometer` int(10) unsigned DEFAULT NULL,
  `arrCloudCeiling` int(10) unsigned DEFAULT NULL,
  `arrVisDistance` int(10) unsigned DEFAULT NULL,
  `arrOAT` int(11) DEFAULT NULL,
  `arrWindMagBearing` int(10) unsigned DEFAULT NULL,
  `arrWindSpeed` int(10) unsigned DEFAULT NULL,
  `arrBarometer` int(10) unsigned DEFAULT NULL,
  `altCloudCeiling` int(10) unsigned DEFAULT NULL,
  `altVisDistance` int(10) unsigned DEFAULT NULL,
  `altOAT` int(11) DEFAULT NULL,
  `altWindMagBearing` int(10) unsigned DEFAULT NULL,
  `altWindSpeed` int(10) unsigned DEFAULT NULL,
  `altBarometer` int(10) unsigned DEFAULT NULL,CREATE TABLE `FlightRoute` (
  `flightRouteId` int(11) NOT NULL AUTO_INCREMENT,
  `flightId` int(11) DEFAULT NULL,
  `routeId` int(11) DEFAULT NULL,
  `calcElaspedMinutes` int(10) unsigned DEFAULT NULL,
  `actElaspedMinutes` int(10) unsigned DEFAULT NULL,
  `arrDateUTC` datetime DEFAULT NULL,
  `planAltitude` int(10) unsigned DEFAULT NULL,
  `planAirspeed` int(10) unsigned DEFAULT NULL,
  `planFuelWeight` int(10) unsigned DEFAULT NULL,
  `minFuelWeight` int(10) unsigned DEFAULT NULL,
  `actFuelWeight` int(10) unsigned DEFAULT NULL,
  `planWindMagBearing` int(10) unsigned DEFAULT NULL,
  `planWindSpeed` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`flightRouteId`),
  UNIQUE KEY `flightRouteId_UNIQUE` (`flightRouteId`),
  KEY `FlightRRouteFK_idx` (`routeId`),
  KEY `FlightRFlightFK_idx` (`flightId`),
  CONSTRAINT `FlightRFlightFK` FOREIGN KEY (`flightId`) REFERENCES `Flight` (`flightId`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `FlightRRouteFK` FOREIGN KEY (`routeId`) REFERENCES `Route` (`routeId`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stores flight specific routing information for each waypoint on the selected route.';

  `passengerWeight` int(10) unsigned DEFAULT NULL,
  `cargoWeight` int(10) unsigned DEFAULT NULL,
  `passengerCount` int(10) unsigned DEFAULT NULL,
  `manifestNotes` mediumtext,
  `minutesTaxi` int(10) unsigned DEFAULT NULL,
  `minutesBurn` int(10) unsigned DEFAULT NULL,
  `minutesCont` int(10) unsigned DEFAULT NULL,
  `minutesRes` int(10) unsigned DEFAULT NULL,
  `minutesAlt` int(10) unsigned DEFAULT NULL,
  `minutesWx` int(10) unsigned DEFAULT NULL,
  `fuelWeightTaxi` int(10) unsigned DEFAULT NULL,
  `fuelWeightBurn` int(10) unsigned DEFAULT NULL,
  `fuelWeightCont` int(10) unsigned DEFAULT NULL,
  `fuelWeightRes` int(10) unsigned DEFAULT NULL,
  `fuelWeightAlt` int(10) unsigned DEFAULT NULL,
  `fuelWeightWx` int(10) unsigned DEFAULT NULL,
  `debriefReport` mediumtext,
  `incidentRecorded` varchar(1) DEFAULT NULL,
  `incidentReport` mediumtext,
  PRIMARY KEY (`flightId`),
  UNIQUE KEY `flightId_UNIQUE` (`flightId`),
  KEY `FlightPilotFK_idx` (`pilotId`),
  KEY `FlightAircraftFK_idx` (`aircraftId`),
  CONSTRAINT `FlightAircraftFK` FOREIGN KEY (`aircraftId`) REFERENCES `Aircraft` (`aircraftId`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `FlightPilotFK` FOREIGN KEY (`pilotId`) REFERENCES `Pilot` (`pilotId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stores data pertaining to an entire flight movement including time, weather, manifest, fuel & status information';
CREATE TABLE `FlightRoute` (
  `flightRouteId` int(11) NOT NULL AUTO_INCREMENT,
  `flightId` int(11) DEFAULT NULL,
  `routeId` int(11) DEFAULT NULL,
  `calcElaspedMinutes` int(10) unsigned DEFAULT NULL,
  `actElaspedMinutes` int(10) unsigned DEFAULT NULL,
  `arrDateUTC` datetime DEFAULT NULL,
  `planAltitude` int(10) unsigned DEFAULT NULL,
  `planAirspeed` int(10) unsigned DEFAULT NULL,
  `planFuelWeight` int(10) unsigned DEFAULT NULL,
  `minFuelWeight` int(10) unsigned DEFAULT NULL,
  `actFuelWeight` int(10) unsigned DEFAULT NULL,
  `planWindMagBearing` int(10) unsigned DEFAULT NULL,
  `planWindSpeed` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`flightRouteId`),
  UNIQUE KEY `flightRouteId_UNIQUE` (`flightRouteId`),
  KEY `FlightRRouteFK_idx` (`routeId`),
  KEY `FlightRFlightFK_idx` (`flightId`),
  CONSTRAINT `FlightRFlightFK` FOREIGN KEY (`flightId`) REFERENCES `Flight` (`flightId`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `FlightRRouteFK` FOREIGN KEY (`routeId`) REFERENCES `Route` (`routeId`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stores flight specific routing information for each waypoint on the selected route.';
CREATE TABLE `Pilot` (
  `pilotId` int(11) NOT NULL AUTO_INCREMENT,
  `firstName` varchar(45) DEFAULT NULL,
  `surname` varchar(45) DEFAULT NULL,
  `callsign` varchar(45) NOT NULL,
  `password1` varchar(45) DEFAULT NULL,
  `password2` varchar(45) DEFAULT NULL,
  `permissions` int(11) NOT NULL DEFAULT '10',
  `minutesDay` int(10) unsigned DEFAULT NULL,
  `minutesNight` int(10) unsigned DEFAULT NULL,
  `totalCompletedFlights` int(10) unsigned DEFAULT NULL,
  `totalPlannedFlights` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`pilotId`),
  UNIQUE KEY `pilotId_UNIQUE` (`pilotId`),
  UNIQUE KEY `callsign_UNIQUE` (`callsign`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stores pilot related info including password and access information';
CREATE TABLE `Route` (
  `routeId` int(11) NOT NULL AUTO_INCREMENT,
  `waypointId` int(11) DEFAULT NULL,
  `seqNo` int(10) unsigned DEFAULT NULL,
  `minAltitude` int(10) unsigned DEFAULT NULL,
  `magBearing` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`routeId`),
  UNIQUE KEY `routeId_UNIQUE` (`routeId`),
  KEY `WaypointFK_idx` (`waypointId`),
  CONSTRAINT `RouteWaypointFK` FOREIGN KEY (`waypointId`) REFERENCES `Waypoint` (`waypointId`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Store an ordered set of waypoints and assciated planning info for flights';
CREATE TABLE `RouteInfo` (
  `routeInfoId` int(11) NOT NULL AUTO_INCREMENT,
  `routeId` int(11) DEFAULT NULL,
  `distanceNm` int(10) unsigned DEFAULT NULL,
  `altitudeMin` int(10) unsigned DEFAULT NULL,
  `remarks` mediumtext,
  PRIMARY KEY (`routeInfoId`),
  UNIQUE KEY `routeInfoId_UNIQUE` (`routeInfoId`),
  KEY `RouteFK_idx` (`routeId`),
  CONSTRAINT `RouteIRouteFK` FOREIGN KEY (`routeId`) REFERENCES `Route` (`routeId`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stores route specific  informaiton';
CREATE TABLE `Runway` (
  `runwayId` int(11) NOT NULL AUTO_INCREMENT,
  `airportId` int(11) DEFAULT NULL,
  `designation` varchar(45) DEFAULT NULL,
  `designationAlt` varchar(45) DEFAULT NULL,
  `surface` int(11) DEFAULT NULL,
  `length` int(10) unsigned DEFAULT NULL,
  `locFreqKhz` int(10) unsigned DEFAULT NULL,
  `locHeading` int(10) unsigned DEFAULT NULL,
  `locAltFreqKhz` int(10) unsigned DEFAULT NULL,
  `locAltHeading` int(10) unsigned DEFAULT NULL,
  `remarks` mediumtext,
  PRIMARY KEY (`runwayId`),
  UNIQUE KEY `runwayId_UNIQUE` (`runwayId`),
  KEY `RunwayAirportFK_idx` (`airportId`),
  CONSTRAINT `RunwayAirportFK` FOREIGN KEY (`airportId`) REFERENCES `Airport` (`airportId`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stores airport runway data';
CREATE TABLE `Waypoint` (
  `waypointId` int(11) NOT NULL AUTO_INCREMENT,
  `type` int(11) DEFAULT NULL,
  `designation` varchar(45) DEFAULT NULL,
  `altitude` int(10) unsigned DEFAULT NULL,
  `latHemi` varchar(1) DEFAULT NULL,
  `latDeg` int(10) unsigned DEFAULT NULL,
  `latMin` int(10) unsigned DEFAULT NULL,
  `latSec` int(10) unsigned DEFAULT NULL,
  `longHemi` varchar(1) DEFAULT NULL,
  `longDeg` int(10) unsigned DEFAULT NULL,
  `longMin` int(10) unsigned DEFAULT NULL,
  `longSec` int(10) unsigned DEFAULT NULL,
  `frequencykHz` int(10) unsigned DEFAULT NULL,
  `remarks` mediumtext,
  PRIMARY KEY (`waypointId`),
  UNIQUE KEY `waypointId_UNIQUE` (`waypointId`),
  UNIQUE KEY `designation_UNIQUE` (`designation`),
  KEY `Designation` (`designation`),
  KEY `Type` (`type`,`designation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Stores waypoint location specific information';
